# Generated by Django 2.2.2 on 2019-07-03 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190702_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='demmand',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='Demanda Finalizada?'),
        ),
        migrations.AlterField(
            model_name='demmand',
            name='deliver_address',
            field=models.ForeignKey(default='4a31d064-9054-4fd8-a11c-812556ad143c', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Address', verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
