# Generated by Django 2.2.2 on 2019-07-03 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190703_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demmand',
            name='deliver_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Address', verbose_name='Endereço'),
        ),
    ]
